### PR TITLE
Added Pack

### PR DESCRIPTION
**Pull request by Ilentian**
added pack Vanilla+ V2 (Marlowww) 

https://www.vanillaplus.net/pack/

### CODE REVIEW

**Comment by the9four** [comment]
you can't just grab the texture pack and make it an epk... you need to change the default files and stuff... that's not gonna work

**Comment by Ilentian** [comment]
> you can't just grab the texture pack and make it an epk... you need to change the default files and stuff... that's not gonna work

Oh im new to this, what do I need to change?

**Comment by the9four** [comment]
you're going to need to download the base epk (https://github.com/eaglerarchive/eaglercraft1.5.2-final/raw/main/javascript/assets.epk) use something like ayunwebepk builder (https://shhnowisnottheti.me/ayunWebEPK/builder.html) look for the texture you want to change and add it
keep in mind that blocks can't go above 16x and will crash if you do add them

**Comment by 3kh0** [comment]
@the9four will this work now?

**Pull request closed without merging**
